{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: 
    name: haproxy-gateway
    namespace: kms
spec:
  gatewayClassName: haproxy-gatewayclass
  listeners:
  - name: vkms
    protocol: TCP
    port: {{ .Values.kms.port }}
    allowedRoutes:
      kinds:
      # - group: gateway.networking.k8s.io
      #   kind: TCPRoute
      - kind: TCPRoute
      namespaces:
        from: Same
{{- end}}